version: '3.6'

services: 

  # Backend API
  resume-parser-api:
    container_name: resume-parser-api
    build: ./
    command: npm start
    #working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    volumes: 
      - ./:/usr/src/smart-brain-api
